services:
  - type: web
    name: sistema-filtro-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: 0
    healthCheckPath: /api/health
